### ISSUE TITLE
Movie Collection Details

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#136]
### Is there a project named like this repo?

- [X] Yes I looked it up and made sure to list it among the projects in case I found it.

### Is your feature request related to a problem? Please describe.

When exploring information about a movie, it is possible to view whether the movie belongs to a specific collection. The user should be able to view the movies in this collection by simply clicking on the collection view.

For a better UX the view should mutate into a dialog showing a recyclerview containing the movies in this collection.

### Describe alternatives you have considered.

Below is a possible code example to implement this functionality:

```java
// Create the transition set that will be used for the animation
TransitionSet set = new TransitionSet();
set.addTransition(new ChangeBounds());
set.addTransition(new ChangeTransform());
set.addTransition(new ChangeImageTransform());

// Create the dialog and inflate the layout
Dialog dialog = new Dialog(this);
dialog.setContentView(R.layout.dialog_layout);

// Find the view that will be used as the starting point for the animation
View startView = findViewById(R.id.start_view);

// Find the view that will be used as the end point for the animation
View endView = dialog.findViewById(R.id.end_view);

// Start the transition with the starting and ending views
TransitionManager.beginDelayedTransition((ViewGroup) startView.getParent(), set);

// Update the layout parameters of the starting view to match those of the ending view
startView.setLayoutParams(endView.getLayoutParams());

// Show the dialog
dialog.show();
```
Or you can use the following [library](https://github.com/skydoves/TransformationLayout)

**Comment by mohit809** [comment]
Yes, this is a valid solution for implementing the desired feature. The code example creates a TransitionSet and adds different transitions to it, such as ChangeBounds, ChangeTransform, and ChangeImageTransform. The dialog is then created and its layout is inflated. The starting and ending views for the animation are identified, and the TransitionManager is used to start the transition with the starting and ending views. Finally, the layout parameters of the starting view are updated to match those of the ending view, and the dialog is shown. This solution uses the Transitions API in Android to provide a smooth and visually appealing animation.
