### ISSUE TITLE
The app crashes when you click on a genre in DiscoveryFragment

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#31]

**Comment by jxareas** [comment]
Working as expected in my forked version of this repository, which at the time of this comment is synced with the main branch.
Tested in emulator (API 26, 31) & physical device (API 32). 
<div align="center">
<img src="https://user-images.githubusercontent.com/60629627/186088753-e0f86df1-60aa-48e2-9c52-917dfd533518.gif" width="200" height="450"/>
</div>

**Comment by Indisparte** [comment]
I am on the branch `feat_substitution_movie_details_w_fragment_movie_details`, I am removing the activities leaving only the MainActivity, I think this Issue is related to the change I am making, related to #30

**Comment by jxareas** [comment]
Surely. At this point, it might be better to refactor the app to a Single Activity Architecture, with a single NavGraph. Instead of dealing with multiple navgraphs, so as not to deal with issues similar to #30.

**Comment by Indisparte** [comment]
Yes that's what I had in mind (_also to translate everything to Kotlin_), the problem with #30  is that using global Action, when I want to use it, calling it simply gives no problems (        `Navigation.findNavController(view).navigate(R.id.action_global_movieDetailsFragment);
`) If I want to pass an argument instead, as in this case a movie, the IDE suggests several solutions like :

-  ```
MovieDetailsFragmentDirections.ActionGlobalMovieDetailsFragment action =
                MovieDetailsFragmentDirections.actionGlobalMovieDetailsFragment(movie);
``` 

-  ```
HomeFragmentDirections.ActionGlobalMovieDetailsFragment action =
                HomeFragmentDirections.actionGlobalMovieDetailsFragment(movie);
```

That is, it recommends me all the directions of the fragments listed in the nav_graph and once the app is launched, it doesn't find that action because it doesn't exist.

**Comment by jxareas** [comment]
In order to solve this issue, you must change the `filterFragment`'s label in the navGraph, from `android:label="{genre.name}"` to `android:label={genre}`
