### ISSUE TITLE
Conversion to Kotlin 

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#39]
To facilitate the use of the latest technologies and methodologies, I decided to switch to using Kotlin

**Comment by jxareas** [comment]
It might also be worthwhile to switch to Kotlin's best practices and naming conventions, such as removing the `m` prefix for non-public non-static fields, a style convention characteristic of the Android Open Source Project's guidelines, [which is no longer popular in Kotlin Android Projects](https://developer.android.com/kotlin/style-guide#naming_2).

**Comment by Indisparte** [comment]
Thanks for the tip, I'll sift through the code I'll sift through the code

**Comment by Indisparte** [comment]
Much of Fragment is now switched to Kotlin, missing adapters and some data classes
