### ISSUE TITLE
LEE RecyclerView (Paging)

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#60]
Loading Error Empty RecyclerView is a custom recyclerview attentive to empty, error, and loading states.

It is about implementing a view that facilitates the use of these states to improve UX

**Comment by jxareas** [comment]
This might be a great addition, even though the empty recycler view is currently being decently handled by a placeholder icon. It'd be great to implement this once the transition to Kotlin is completed.

**Comment by Indisparte** [comment]
I am currently in the process of implementing [this library](https://github.com/Indisparte/SensibleRecyclerView) and integrating it into the project

**Comment by Indisparte** [comment]
I implemented an **alpha** of [this library](https://github.com/Indisparte/SensibleRecyclerView) and now I will proceed to replace it in the whole project

**Comment by Indisparte** [comment]
Un grande passo avanti per ottenere questo risultato sarebbe utilizzare [Paging](https://developer.android.com/topic/libraries/architecture/paging/v3-overview)
