### ISSUE TITLE
DiscoverFragment crashes the app when clicking multiple genres at the same time

### ISSUE THREAD

**Issue by jxareas** [Indisparte/CineMates#62]
It might be noteworthy to mention, this is a pretty common issue when using the `Jetpack Navigation` library. Such a problem is usually handled via a `safeNavigate` extension function.

![image](https://user-images.githubusercontent.com/60629627/187162509-b9232e35-69ca-4a1b-8a3f-affeb0c795ff.png)

**Comment by Indisparte** [comment]
More than one gender filter can now be applied to the search.
