### ISSUE TITLE
Fix Images Page in `MovieDetailsFragment` ViewPager

### ISSUE THREAD

**Issue by jxareas** [Indisparte/CineMates#84]
When visiting several movies, the images of the latest movies are appended at the end, which is not the intended behavior, as can be evidenced by the following recording:

https://user-images.githubusercontent.com/60629627/197072677-605484db-5c76-455e-a7b4-49dba36ef986.mp4

**Comment by Indisparte** [comment]
We should reset the entire view model associated with the MovieDetailsFragment, whe the stack is popped

**Comment by jxareas** [comment]
I was rather thinking of using a custom getter, that'll be called every time the property is accessed. I think that might solve this issue.

**Comment by Indisparte** [comment]
Of course this is also another great solution I agree
